### PR TITLE
adding ability to use eyaml_gpg on RHEV based systems

### PR DESCRIPTION
**Pull request by smbambling**
This is an updated version of PR #43

Add the ability to install/configure hiera-eyaml-gpg.

Configures needed hiera.yaml properties
Installs needed gems
Generate GPG keyring

### CODE REVIEW

**Comment by smbambling** [comment]
Any update or issue on this PR ?

**Comment by smbambling** [comment]
@hunner: Any suggestion on this ?

I'm thinking maybe its a little out of scope for the module to generate the GPG Keyring...but maybe have some detailed notes in the README on it.

**Comment by smbambling** [comment]
@jyaworski: Do you use eyaml GPG or have any thoughts or suggestions on this ?

**Comment by hunner** [comment]
Sorry, just getting back to hiera. I made some changes recently in the way extension packaging is handled (https://github.com/hunner/puppet-hiera/pull/117) so if you could rebase and match that, that would be great. Sorry for the extra work.

**Comment by smbambling** [comment]
Will do I'll get this done early EST tomorrow

**Comment by smbambling** [comment]
Sorry just got back to this.  I've up got this branch back up to date with master.  though i'm having some issue with squashing after my merge/rebase.

I'd still like some opinions on if the module should try to install GPG packages and create the GPG keys...seems like a good idea but might be out of scope depending on the complexity of packages need on different systems.

**Comment by jyaworski** [comment]
@smbambling I would say we can assume GPG is installed, so don't manage the packages. Or, if we do manage the packages, default to off. Personally I think it's out of scope.

Creating the keys is also out of scope IMO, but it's more in-scope than managing the packages.

**Comment by smbambling** [comment]
@jyaworski: Yeah I agree after sleeping on it.  I've removed the code that would manage those packages and create the keys..but have added some simple docs on it.

**Comment by smbambling** [comment]
@hunner @jyaworski any other suggestions ?

**Comment by jyaworski** [comment]
I would say squash and we're good-to-go.

**Pull request merged**
